[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "scripts"
solc = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
via_ir = true
ffi = true
fs_permissions = [{ access = "read", path = "./" }]

[fuzz]
runs = 1024

[invariant]
runs = 64
depth = 32
fail_on_revert = false
